### ISSUE TITLE
[SERVER/CLIENT] #1 개발환경구축

### ISSUE THREAD

**Issue by riverpark94** [riverpark94/iamport#1]
### ISSUE
- Group: `server`, `client`
- Detail: fix actions from client redux

### TODO
1. [ ] server와 client 폴더 나누기
2. [ ] nodejs 환경 구축
3. [ ] React 환경 구축

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 2h`
- Group : `server`, `client`
- Sprint: `Sprint__1__`
- Urgency: `Low`
